# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 382318f01bbdd41d18feda0f5d80937360c860b815c8a49fe1ff0f39da0abf66237449ec314699f8db46f306bb7592889a8ecca2edf246fc7b14e711e22b2456

test:
  secret_key_base: 2974140aac5b449efcd64d33c38c7f5098b4ee90542059f6109be16617c5e7bb47eabed4d117e447c531b0259768603da3b44f45fbe3882566676bad8b8a862a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
